repos:
- repo: local
  hooks:      
    #- id: isort
    #  name: isort
    #  entry: isort
    #  language: system
    #  types: [python]
    #  stages: [pre-commit]
#
    #- id: black
    #  name: black
    #  entry: black
    #  args: [--config=pyproject.toml]
    #  language: system
    #  types: [python]
    #  stages: [pre-commit]

    - id: ruff-linter
      name: ruff
      entry: ruff check
      args: [--fix, --config=pyproject.toml]
      language: system
      types: [python]
      stages: [pre-commit]

    - id: ruff-formatter
      name: ruff
      entry: ruff format
      args: [--config=pyproject.toml]
      language: system
      types: [python]
      stages: [pre-commit]

    - id: mypy
      name: mypy
      entry: mypy
      args: [--config-file=pyproject.toml, --pretty]
      language: system
      types: [python]
      stages: [pre-commit]



